apiVersion: v1
kind: Service
metadata:
  name: bankc-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: bankc-backend
    {{- include "bank-compliance.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.backend.service.dnsLabel | quote }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: bankc-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
    - name: http-alt
      port: {{ .Values.backend.service.altPort }}
      targetPort: {{ .Values.backend.service.targetPort }}
