apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bank-compliance.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_OPENAI_ENDPOINT: {{ .Values.secrets.openaiEndpoint | quote }}
  AZURE_API_KEY: {{ .Values.secrets.openaiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
