{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: {{ include "bank-compliance.name" . }}-sa
    {{- include "bank-compliance.labels" . | nindent 4 }}
{{- end }}
