sonar.projectKey=Ganesan-kasi_terraform-azure-iac
sonar.organization=ganesan-kasi
sonar.projectName=terraform-azure-iac
sonar.sources=app/tax-advisor,modules,platform,workloads
sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**
sonar.sourceEncoding=UTF-8
