apiVersion: v1
kind: ServiceAccount
metadata:
  name: bankc-sa
  namespace: bank-compliance
  annotations:
    azure.workload.identity/client-id: "99ab7987-3989-46c3-bae9-92279be16608"
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: bank-compliance-sa
