persistence:
  enabled: true
  storageClassName: "managed-csi"
  size: 4Gi
  accessModes:
    - ReadWriteOnce

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
