apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
  namespace: bank-compliance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm-proxy
  template:
    metadata:
      labels:
        app: litellm-proxy
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: bankc-sa
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-v1.41.0
          args: ["--config", "/etc/litellm/config.yaml", "--port", "4000"]
          envFrom:
            - secretRef:
                name: litellm-secret
          volumeMounts:
            - name: litellm-config
              mountPath: /etc/litellm
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "300Mi"
          ports:
            - containerPort: 4000
      volumes:
        - name: litellm-config
          configMap:
            name: litellm-config
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: bank-compliance
spec:
  selector:
    app: litellm-proxy
  ports:
    - port: 4000
      targetPort: 4000
