parameters:
  - name: workingDirectory
    type: string
  - name: environmentName
    type: string
  - name: azureSubscriptionName
    type: string

steps:
- task: AzureCLI@2
  displayName: 'Terraform validate - ${{ parameters.environmentName }}'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform -chdir=${{ parameters.workingDirectory }} validate
