parameters:
  - name: workingDirectory
    type: string
  - name: environmentName
    type: string

steps:
- task: AzureCLI@2
  displayName: 'Terraform apply - ${{ parameters.environmentName }}'
  inputs:
    azureSubscription: '${{ parameters.environmentName == ''dev'' && ''dev'' || parameters.environmentName == ''staging'' && ''staging'' || ''prod'' }}'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform -chdir=${{ parameters.workingDirectory }} apply -auto-approve -var-file=environments/${{ parameters.environmentName }}/terraform.tfvars tfplan.out
