parameters:
  - name: workingDirectory
    type: string
  - name: environmentName
    type: string
  - name: backendResourceGroup
    type: string

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.7.5'

- task: AzureCLI@2
  displayName: 'Terraform init - ${{ parameters.environmentName }}'
  inputs:
    azureSubscription: ${{ parameters.environmentName }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform -chdir=${{ parameters.workingDirectory }} init -input=false \
        -backend-config=resource_group_name=${{ parameters.backendResourceGroup }} \
        -backend-config=storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT) \
        -backend-config=container_name=$(TF_BACKEND_CONTAINER) \
        -backend-config=key=${{ parameters.environmentName }}/terraform.tfstate
